/** Auto-generated by scripts/sync-recipe-ids.mjs — do not edit manually */
export const RECIPE_IDS = [
  "r-aloo-paratha",
  "r-poha",
  "r-idli-sambar",
  "r-upma",
  "r-spinach-egg",
  "r-dal-tadka",
  "r-rajma-chawal",
  "r-chole-bhature",
  "r-veg-pulao",
  "r-paneer-bhurji",
  "r-paneer-butter-masala",
  "r-khichdi",
  "r-palak-dal-roti",
  "r-fried-rice",
  "r-yogurt-curry",
  "r-pasta",
  "r-egg-curry-rice"
] as const;
